/* tslint:disable */
/* eslint-disable */
/**
 * Snap Sync API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumResponseDto
 */
export interface AlbumResponseDto {
    /**
     * 
     * @type {string}
     * @memberof AlbumResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumResponseDto
     */
    albumName: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumResponseDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the AlbumResponseDto interface.
 */
export function instanceOfAlbumResponseDto(value: object): value is AlbumResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('albumName' in value) || value['albumName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AlbumResponseDtoFromJSON(json: any): AlbumResponseDto {
    return AlbumResponseDtoFromJSONTyped(json, false);
}

export function AlbumResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'albumName': json['albumName'],
        'createdAt': json['createdAt'],
    };
}

export function AlbumResponseDtoToJSON(json: any): AlbumResponseDto {
    return AlbumResponseDtoToJSONTyped(json, false);
}

export function AlbumResponseDtoToJSONTyped(value?: AlbumResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'albumName': value['albumName'],
        'createdAt': value['createdAt'],
    };
}

