/* tslint:disable */
/* eslint-disable */
/**
 * Snap Sync API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAlbumDto
 */
export interface CreateAlbumDto {
    /**
     * 
     * @type {string}
     * @memberof CreateAlbumDto
     */
    albumName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAlbumDto
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateAlbumDto interface.
 */
export function instanceOfCreateAlbumDto(value: object): value is CreateAlbumDto {
    if (!('albumName' in value) || value['albumName'] === undefined) return false;
    return true;
}

export function CreateAlbumDtoFromJSON(json: any): CreateAlbumDto {
    return CreateAlbumDtoFromJSONTyped(json, false);
}

export function CreateAlbumDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAlbumDto {
    if (json == null) {
        return json;
    }
    return {
        
        'albumName': json['albumName'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateAlbumDtoToJSON(json: any): CreateAlbumDto {
    return CreateAlbumDtoToJSONTyped(json, false);
}

export function CreateAlbumDtoToJSONTyped(value?: CreateAlbumDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'albumName': value['albumName'],
        'description': value['description'],
    };
}

