/* tslint:disable */
/* eslint-disable */
/**
 * Snap Sync API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlbumResponseDto,
  CreateAlbumDto,
} from '../models/index';
import {
    AlbumResponseDtoFromJSON,
    AlbumResponseDtoToJSON,
    CreateAlbumDtoFromJSON,
    CreateAlbumDtoToJSON,
} from '../models/index';

export interface CreateAlbumRequest {
    createAlbumDto: CreateAlbumDto;
}

/**
 * 
 */
export class AlbumApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAlbum without sending the request
     */
    async createAlbumRequestOpts(requestParameters: CreateAlbumRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createAlbumDto'] == null) {
            throw new runtime.RequiredError(
                'createAlbumDto',
                'Required parameter "createAlbumDto" was null or undefined when calling createAlbum().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/albums`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAlbumDtoToJSON(requestParameters['createAlbumDto']),
        };
    }

    /**
     * Create a new album
     */
    async createAlbumRaw(requestParameters: CreateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlbumResponseDto>> {
        const requestOptions = await this.createAlbumRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a new album
     */
    async createAlbum(requestParameters: CreateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlbumResponseDto> {
        const response = await this.createAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllAlbums without sending the request
     */
    async getAllAlbumsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/albums`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all albums
     */
    async getAllAlbumsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlbumResponseDto>>> {
        const requestOptions = await this.getAllAlbumsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlbumResponseDtoFromJSON));
    }

    /**
     * Get all albums
     */
    async getAllAlbums(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlbumResponseDto>> {
        const response = await this.getAllAlbumsRaw(initOverrides);
        return await response.value();
    }

}
